/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MotoristaRouteImport } from './routes/motorista'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as ClienteRedefinirSenhaRouteImport } from './routes/cliente.redefinir-senha'
import { Route as ClienteLoginRouteImport } from './routes/cliente.login'
import { Route as ClienteEsqueciSenhaRouteImport } from './routes/cliente.esqueci-senha'
import { Route as ClienteCadastroRouteImport } from './routes/cliente.cadastro'
import { Route as ClienteAppRouteImport } from './routes/cliente.app'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTarifasRouteImport } from './routes/_authenticated/tarifas'
import { Route as AuthenticatedMuralRouteImport } from './routes/_authenticated/mural'
import { Route as AuthenticatedMotoristasRouteImport } from './routes/_authenticated/motoristas'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedInstrucoesRouteImport } from './routes/_authenticated/instrucoes'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorridasRouteImport } from './routes/_authenticated/corridas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedChatMotoristasRouteImport } from './routes/_authenticated/chat-motoristas'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaRoute = MotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/cliente/',
  path: '/cliente/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRedefinirSenhaRoute = ClienteRedefinirSenhaRouteImport.update({
  id: '/cliente/redefinir-senha',
  path: '/cliente/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteLoginRoute = ClienteLoginRouteImport.update({
  id: '/cliente/login',
  path: '/cliente/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteEsqueciSenhaRoute = ClienteEsqueciSenhaRouteImport.update({
  id: '/cliente/esqueci-senha',
  path: '/cliente/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteCadastroRoute = ClienteCadastroRouteImport.update({
  id: '/cliente/cadastro',
  path: '/cliente/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteAppRoute = ClienteAppRouteImport.update({
  id: '/cliente/app',
  path: '/cliente/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTarifasRoute = AuthenticatedTarifasRouteImport.update({
  id: '/tarifas',
  path: '/tarifas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMuralRoute = AuthenticatedMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMotoristasRoute = AuthenticatedMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstrucoesRoute = AuthenticatedInstrucoesRouteImport.update({
  id: '/instrucoes',
  path: '/instrucoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCorridasRoute = AuthenticatedCorridasRouteImport.update({
  id: '/corridas',
  path: '/corridas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatMotoristasRoute =
  AuthenticatedChatMotoristasRouteImport.update({
    id: '/chat-motoristas',
    path: '/chat-motoristas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/motorista': typeof MotoristaRoute
  '/painel': typeof PainelRoute
  '/parceiros': typeof ParceirosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/chat-motoristas': typeof AuthenticatedChatMotoristasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corridas': typeof AuthenticatedCorridasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/instrucoes': typeof AuthenticatedInstrucoesRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/mural': typeof AuthenticatedMuralRoute
  '/tarifas': typeof AuthenticatedTarifasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/cliente/app': typeof ClienteAppRoute
  '/cliente/cadastro': typeof ClienteCadastroRoute
  '/cliente/esqueci-senha': typeof ClienteEsqueciSenhaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/redefinir-senha': typeof ClienteRedefinirSenhaRoute
  '/cliente/': typeof ClienteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/motorista': typeof MotoristaRoute
  '/painel': typeof PainelRoute
  '/parceiros': typeof ParceirosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/chat-motoristas': typeof AuthenticatedChatMotoristasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corridas': typeof AuthenticatedCorridasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/instrucoes': typeof AuthenticatedInstrucoesRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/mural': typeof AuthenticatedMuralRoute
  '/tarifas': typeof AuthenticatedTarifasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/cliente/app': typeof ClienteAppRoute
  '/cliente/cadastro': typeof ClienteCadastroRoute
  '/cliente/esqueci-senha': typeof ClienteEsqueciSenhaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/redefinir-senha': typeof ClienteRedefinirSenhaRoute
  '/cliente': typeof ClienteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/login': typeof LoginRoute
  '/motorista': typeof MotoristaRoute
  '/painel': typeof PainelRoute
  '/parceiros': typeof ParceirosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/chat-motoristas': typeof AuthenticatedChatMotoristasRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/corridas': typeof AuthenticatedCorridasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/instrucoes': typeof AuthenticatedInstrucoesRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/motoristas': typeof AuthenticatedMotoristasRoute
  '/_authenticated/mural': typeof AuthenticatedMuralRoute
  '/_authenticated/tarifas': typeof AuthenticatedTarifasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/cliente/app': typeof ClienteAppRoute
  '/cliente/cadastro': typeof ClienteCadastroRoute
  '/cliente/esqueci-senha': typeof ClienteEsqueciSenhaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/redefinir-senha': typeof ClienteRedefinirSenhaRoute
  '/cliente/': typeof ClienteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/login'
    | '/motorista'
    | '/painel'
    | '/parceiros'
    | '/reset-password'
    | '/chat-motoristas'
    | '/clientes'
    | '/configuracoes'
    | '/corridas'
    | '/dashboard'
    | '/financeiro'
    | '/historico'
    | '/instrucoes'
    | '/mensagens'
    | '/motoristas'
    | '/mural'
    | '/tarifas'
    | '/usuarios'
    | '/cliente/app'
    | '/cliente/cadastro'
    | '/cliente/esqueci-senha'
    | '/cliente/login'
    | '/cliente/redefinir-senha'
    | '/cliente/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/login'
    | '/motorista'
    | '/painel'
    | '/parceiros'
    | '/reset-password'
    | '/chat-motoristas'
    | '/clientes'
    | '/configuracoes'
    | '/corridas'
    | '/dashboard'
    | '/financeiro'
    | '/historico'
    | '/instrucoes'
    | '/mensagens'
    | '/motoristas'
    | '/mural'
    | '/tarifas'
    | '/usuarios'
    | '/cliente/app'
    | '/cliente/cadastro'
    | '/cliente/esqueci-senha'
    | '/cliente/login'
    | '/cliente/redefinir-senha'
    | '/cliente'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/como-funciona'
    | '/login'
    | '/motorista'
    | '/painel'
    | '/parceiros'
    | '/reset-password'
    | '/_authenticated/chat-motoristas'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/corridas'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/historico'
    | '/_authenticated/instrucoes'
    | '/_authenticated/mensagens'
    | '/_authenticated/motoristas'
    | '/_authenticated/mural'
    | '/_authenticated/tarifas'
    | '/_authenticated/usuarios'
    | '/cliente/app'
    | '/cliente/cadastro'
    | '/cliente/esqueci-senha'
    | '/cliente/login'
    | '/cliente/redefinir-senha'
    | '/cliente/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  LoginRoute: typeof LoginRoute
  MotoristaRoute: typeof MotoristaRoute
  PainelRoute: typeof PainelRoute
  ParceirosRoute: typeof ParceirosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ClienteAppRoute: typeof ClienteAppRoute
  ClienteCadastroRoute: typeof ClienteCadastroRoute
  ClienteEsqueciSenhaRoute: typeof ClienteEsqueciSenhaRoute
  ClienteLoginRoute: typeof ClienteLoginRoute
  ClienteRedefinirSenhaRoute: typeof ClienteRedefinirSenhaRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista': {
      id: '/motorista'
      path: '/motorista'
      fullPath: '/motorista'
      preLoaderRoute: typeof MotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/cliente'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/redefinir-senha': {
      id: '/cliente/redefinir-senha'
      path: '/cliente/redefinir-senha'
      fullPath: '/cliente/redefinir-senha'
      preLoaderRoute: typeof ClienteRedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/login': {
      id: '/cliente/login'
      path: '/cliente/login'
      fullPath: '/cliente/login'
      preLoaderRoute: typeof ClienteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/esqueci-senha': {
      id: '/cliente/esqueci-senha'
      path: '/cliente/esqueci-senha'
      fullPath: '/cliente/esqueci-senha'
      preLoaderRoute: typeof ClienteEsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/cadastro': {
      id: '/cliente/cadastro'
      path: '/cliente/cadastro'
      fullPath: '/cliente/cadastro'
      preLoaderRoute: typeof ClienteCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/app': {
      id: '/cliente/app'
      path: '/cliente/app'
      fullPath: '/cliente/app'
      preLoaderRoute: typeof ClienteAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarifas': {
      id: '/_authenticated/tarifas'
      path: '/tarifas'
      fullPath: '/tarifas'
      preLoaderRoute: typeof AuthenticatedTarifasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mural': {
      id: '/_authenticated/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof AuthenticatedMuralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/motoristas': {
      id: '/_authenticated/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof AuthenticatedMotoristasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instrucoes': {
      id: '/_authenticated/instrucoes'
      path: '/instrucoes'
      fullPath: '/instrucoes'
      preLoaderRoute: typeof AuthenticatedInstrucoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corridas': {
      id: '/_authenticated/corridas'
      path: '/corridas'
      fullPath: '/corridas'
      preLoaderRoute: typeof AuthenticatedCorridasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat-motoristas': {
      id: '/_authenticated/chat-motoristas'
      path: '/chat-motoristas'
      fullPath: '/chat-motoristas'
      preLoaderRoute: typeof AuthenticatedChatMotoristasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChatMotoristasRoute: typeof AuthenticatedChatMotoristasRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCorridasRoute: typeof AuthenticatedCorridasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedInstrucoesRoute: typeof AuthenticatedInstrucoesRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedMotoristasRoute: typeof AuthenticatedMotoristasRoute
  AuthenticatedMuralRoute: typeof AuthenticatedMuralRoute
  AuthenticatedTarifasRoute: typeof AuthenticatedTarifasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatMotoristasRoute: AuthenticatedChatMotoristasRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCorridasRoute: AuthenticatedCorridasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedInstrucoesRoute: AuthenticatedInstrucoesRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedMotoristasRoute: AuthenticatedMotoristasRoute,
  AuthenticatedMuralRoute: AuthenticatedMuralRoute,
  AuthenticatedTarifasRoute: AuthenticatedTarifasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  LoginRoute: LoginRoute,
  MotoristaRoute: MotoristaRoute,
  PainelRoute: PainelRoute,
  ParceirosRoute: ParceirosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ClienteAppRoute: ClienteAppRoute,
  ClienteCadastroRoute: ClienteCadastroRoute,
  ClienteEsqueciSenhaRoute: ClienteEsqueciSenhaRoute,
  ClienteLoginRoute: ClienteLoginRoute,
  ClienteRedefinirSenhaRoute: ClienteRedefinirSenhaRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
