/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MotociclistaRouteImport } from './routes/motociclista'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as OperadorLoginRouteImport } from './routes/operador.login'
import { Route as ClienteRedefinirSenhaRouteImport } from './routes/cliente.redefinir-senha'
import { Route as ClienteLoginRouteImport } from './routes/cliente.login'
import { Route as ClienteEsqueciSenhaRouteImport } from './routes/cliente.esqueci-senha'
import { Route as ClienteCadastroRouteImport } from './routes/cliente.cadastro'
import { Route as ClienteAppRouteImport } from './routes/cliente.app'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTermosConfigRouteImport } from './routes/_authenticated/termos-config'
import { Route as AuthenticatedTarifasRouteImport } from './routes/_authenticated/tarifas'
import { Route as AuthenticatedMuralRouteImport } from './routes/_authenticated/mural'
import { Route as AuthenticatedMotociclistasRouteImport } from './routes/_authenticated/motociclistas'
import { Route as AuthenticatedInstrucoesRouteImport } from './routes/_authenticated/instrucoes'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCorridasRouteImport } from './routes/_authenticated/corridas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedChatMotociclistasRouteImport } from './routes/_authenticated/chat-motociclistas'
import { Route as AuthenticatedChatClientesRouteImport } from './routes/_authenticated/chat-clientes'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as ClienteAppIndexRouteImport } from './routes/cliente.app.index'
import { Route as ClienteAppSenhaRouteImport } from './routes/cliente.app.senha'
import { Route as ClienteAppPerfilRouteImport } from './routes/cliente.app.perfil'
import { Route as ClienteAppHistoricoRouteImport } from './routes/cliente.app.historico'
import { Route as ClienteAppChatRouteImport } from './routes/cliente.app.chat'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MotociclistaRoute = MotociclistaRouteImport.update({
  id: '/motociclista',
  path: '/motociclista',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/cliente/',
  path: '/cliente/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorLoginRoute = OperadorLoginRouteImport.update({
  id: '/operador/login',
  path: '/operador/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRedefinirSenhaRoute = ClienteRedefinirSenhaRouteImport.update({
  id: '/cliente/redefinir-senha',
  path: '/cliente/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteLoginRoute = ClienteLoginRouteImport.update({
  id: '/cliente/login',
  path: '/cliente/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteEsqueciSenhaRoute = ClienteEsqueciSenhaRouteImport.update({
  id: '/cliente/esqueci-senha',
  path: '/cliente/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteCadastroRoute = ClienteCadastroRouteImport.update({
  id: '/cliente/cadastro',
  path: '/cliente/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteAppRoute = ClienteAppRouteImport.update({
  id: '/cliente/app',
  path: '/cliente/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTermosConfigRoute =
  AuthenticatedTermosConfigRouteImport.update({
    id: '/termos-config',
    path: '/termos-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTarifasRoute = AuthenticatedTarifasRouteImport.update({
  id: '/tarifas',
  path: '/tarifas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMuralRoute = AuthenticatedMuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMotociclistasRoute =
  AuthenticatedMotociclistasRouteImport.update({
    id: '/motociclistas',
    path: '/motociclistas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstrucoesRoute = AuthenticatedInstrucoesRouteImport.update({
  id: '/instrucoes',
  path: '/instrucoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCorridasRoute = AuthenticatedCorridasRouteImport.update({
  id: '/corridas',
  path: '/corridas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatMotociclistasRoute =
  AuthenticatedChatMotociclistasRouteImport.update({
    id: '/chat-motociclistas',
    path: '/chat-motociclistas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatClientesRoute =
  AuthenticatedChatClientesRouteImport.update({
    id: '/chat-clientes',
    path: '/chat-clientes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ClienteAppIndexRoute = ClienteAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteAppRoute,
} as any)
const ClienteAppSenhaRoute = ClienteAppSenhaRouteImport.update({
  id: '/senha',
  path: '/senha',
  getParentRoute: () => ClienteAppRoute,
} as any)
const ClienteAppPerfilRoute = ClienteAppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClienteAppRoute,
} as any)
const ClienteAppHistoricoRoute = ClienteAppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => ClienteAppRoute,
} as any)
const ClienteAppChatRoute = ClienteAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ClienteAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/instalar': typeof InstalarRoute
  '/motociclista': typeof MotociclistaRoute
  '/painel': typeof PainelRoute
  '/parceiros': typeof ParceirosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/chat-clientes': typeof AuthenticatedChatClientesRoute
  '/chat-motociclistas': typeof AuthenticatedChatMotociclistasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corridas': typeof AuthenticatedCorridasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/instrucoes': typeof AuthenticatedInstrucoesRoute
  '/motociclistas': typeof AuthenticatedMotociclistasRoute
  '/mural': typeof AuthenticatedMuralRoute
  '/tarifas': typeof AuthenticatedTarifasRoute
  '/termos-config': typeof AuthenticatedTermosConfigRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/cliente/app': typeof ClienteAppRouteWithChildren
  '/cliente/cadastro': typeof ClienteCadastroRoute
  '/cliente/esqueci-senha': typeof ClienteEsqueciSenhaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/redefinir-senha': typeof ClienteRedefinirSenhaRoute
  '/operador/login': typeof OperadorLoginRoute
  '/cliente/': typeof ClienteIndexRoute
  '/cliente/app/chat': typeof ClienteAppChatRoute
  '/cliente/app/historico': typeof ClienteAppHistoricoRoute
  '/cliente/app/perfil': typeof ClienteAppPerfilRoute
  '/cliente/app/senha': typeof ClienteAppSenhaRoute
  '/cliente/app/': typeof ClienteAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/instalar': typeof InstalarRoute
  '/motociclista': typeof MotociclistaRoute
  '/painel': typeof PainelRoute
  '/parceiros': typeof ParceirosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/chat-clientes': typeof AuthenticatedChatClientesRoute
  '/chat-motociclistas': typeof AuthenticatedChatMotociclistasRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/corridas': typeof AuthenticatedCorridasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/instrucoes': typeof AuthenticatedInstrucoesRoute
  '/motociclistas': typeof AuthenticatedMotociclistasRoute
  '/mural': typeof AuthenticatedMuralRoute
  '/tarifas': typeof AuthenticatedTarifasRoute
  '/termos-config': typeof AuthenticatedTermosConfigRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/cliente/cadastro': typeof ClienteCadastroRoute
  '/cliente/esqueci-senha': typeof ClienteEsqueciSenhaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/redefinir-senha': typeof ClienteRedefinirSenhaRoute
  '/operador/login': typeof OperadorLoginRoute
  '/cliente': typeof ClienteIndexRoute
  '/cliente/app/chat': typeof ClienteAppChatRoute
  '/cliente/app/historico': typeof ClienteAppHistoricoRoute
  '/cliente/app/perfil': typeof ClienteAppPerfilRoute
  '/cliente/app/senha': typeof ClienteAppSenhaRoute
  '/cliente/app': typeof ClienteAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/como-funciona': typeof ComoFuncionaRoute
  '/instalar': typeof InstalarRoute
  '/motociclista': typeof MotociclistaRoute
  '/painel': typeof PainelRoute
  '/parceiros': typeof ParceirosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/chat-clientes': typeof AuthenticatedChatClientesRoute
  '/_authenticated/chat-motociclistas': typeof AuthenticatedChatMotociclistasRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/corridas': typeof AuthenticatedCorridasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/instrucoes': typeof AuthenticatedInstrucoesRoute
  '/_authenticated/motociclistas': typeof AuthenticatedMotociclistasRoute
  '/_authenticated/mural': typeof AuthenticatedMuralRoute
  '/_authenticated/tarifas': typeof AuthenticatedTarifasRoute
  '/_authenticated/termos-config': typeof AuthenticatedTermosConfigRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/cliente/app': typeof ClienteAppRouteWithChildren
  '/cliente/cadastro': typeof ClienteCadastroRoute
  '/cliente/esqueci-senha': typeof ClienteEsqueciSenhaRoute
  '/cliente/login': typeof ClienteLoginRoute
  '/cliente/redefinir-senha': typeof ClienteRedefinirSenhaRoute
  '/operador/login': typeof OperadorLoginRoute
  '/cliente/': typeof ClienteIndexRoute
  '/cliente/app/chat': typeof ClienteAppChatRoute
  '/cliente/app/historico': typeof ClienteAppHistoricoRoute
  '/cliente/app/perfil': typeof ClienteAppPerfilRoute
  '/cliente/app/senha': typeof ClienteAppSenhaRoute
  '/cliente/app/': typeof ClienteAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/instalar'
    | '/motociclista'
    | '/painel'
    | '/parceiros'
    | '/privacidade'
    | '/quem-somos'
    | '/reset-password'
    | '/termos'
    | '/audit-log'
    | '/chat-clientes'
    | '/chat-motociclistas'
    | '/clientes'
    | '/configuracoes'
    | '/corridas'
    | '/dashboard'
    | '/financeiro'
    | '/historico'
    | '/instrucoes'
    | '/motociclistas'
    | '/mural'
    | '/tarifas'
    | '/termos-config'
    | '/usuarios'
    | '/cliente/app'
    | '/cliente/cadastro'
    | '/cliente/esqueci-senha'
    | '/cliente/login'
    | '/cliente/redefinir-senha'
    | '/operador/login'
    | '/cliente/'
    | '/cliente/app/chat'
    | '/cliente/app/historico'
    | '/cliente/app/perfil'
    | '/cliente/app/senha'
    | '/cliente/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/instalar'
    | '/motociclista'
    | '/painel'
    | '/parceiros'
    | '/privacidade'
    | '/quem-somos'
    | '/reset-password'
    | '/termos'
    | '/audit-log'
    | '/chat-clientes'
    | '/chat-motociclistas'
    | '/clientes'
    | '/configuracoes'
    | '/corridas'
    | '/dashboard'
    | '/financeiro'
    | '/historico'
    | '/instrucoes'
    | '/motociclistas'
    | '/mural'
    | '/tarifas'
    | '/termos-config'
    | '/usuarios'
    | '/cliente/cadastro'
    | '/cliente/esqueci-senha'
    | '/cliente/login'
    | '/cliente/redefinir-senha'
    | '/operador/login'
    | '/cliente'
    | '/cliente/app/chat'
    | '/cliente/app/historico'
    | '/cliente/app/perfil'
    | '/cliente/app/senha'
    | '/cliente/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/como-funciona'
    | '/instalar'
    | '/motociclista'
    | '/painel'
    | '/parceiros'
    | '/privacidade'
    | '/quem-somos'
    | '/reset-password'
    | '/termos'
    | '/_authenticated/audit-log'
    | '/_authenticated/chat-clientes'
    | '/_authenticated/chat-motociclistas'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/corridas'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/historico'
    | '/_authenticated/instrucoes'
    | '/_authenticated/motociclistas'
    | '/_authenticated/mural'
    | '/_authenticated/tarifas'
    | '/_authenticated/termos-config'
    | '/_authenticated/usuarios'
    | '/cliente/app'
    | '/cliente/cadastro'
    | '/cliente/esqueci-senha'
    | '/cliente/login'
    | '/cliente/redefinir-senha'
    | '/operador/login'
    | '/cliente/'
    | '/cliente/app/chat'
    | '/cliente/app/historico'
    | '/cliente/app/perfil'
    | '/cliente/app/senha'
    | '/cliente/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  InstalarRoute: typeof InstalarRoute
  MotociclistaRoute: typeof MotociclistaRoute
  PainelRoute: typeof PainelRoute
  ParceirosRoute: typeof ParceirosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  ClienteAppRoute: typeof ClienteAppRouteWithChildren
  ClienteCadastroRoute: typeof ClienteCadastroRoute
  ClienteEsqueciSenhaRoute: typeof ClienteEsqueciSenhaRoute
  ClienteLoginRoute: typeof ClienteLoginRoute
  ClienteRedefinirSenhaRoute: typeof ClienteRedefinirSenhaRoute
  OperadorLoginRoute: typeof OperadorLoginRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motociclista': {
      id: '/motociclista'
      path: '/motociclista'
      fullPath: '/motociclista'
      preLoaderRoute: typeof MotociclistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/cliente'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/login': {
      id: '/operador/login'
      path: '/operador/login'
      fullPath: '/operador/login'
      preLoaderRoute: typeof OperadorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/redefinir-senha': {
      id: '/cliente/redefinir-senha'
      path: '/cliente/redefinir-senha'
      fullPath: '/cliente/redefinir-senha'
      preLoaderRoute: typeof ClienteRedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/login': {
      id: '/cliente/login'
      path: '/cliente/login'
      fullPath: '/cliente/login'
      preLoaderRoute: typeof ClienteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/esqueci-senha': {
      id: '/cliente/esqueci-senha'
      path: '/cliente/esqueci-senha'
      fullPath: '/cliente/esqueci-senha'
      preLoaderRoute: typeof ClienteEsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/cadastro': {
      id: '/cliente/cadastro'
      path: '/cliente/cadastro'
      fullPath: '/cliente/cadastro'
      preLoaderRoute: typeof ClienteCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/app': {
      id: '/cliente/app'
      path: '/cliente/app'
      fullPath: '/cliente/app'
      preLoaderRoute: typeof ClienteAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/termos-config': {
      id: '/_authenticated/termos-config'
      path: '/termos-config'
      fullPath: '/termos-config'
      preLoaderRoute: typeof AuthenticatedTermosConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarifas': {
      id: '/_authenticated/tarifas'
      path: '/tarifas'
      fullPath: '/tarifas'
      preLoaderRoute: typeof AuthenticatedTarifasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mural': {
      id: '/_authenticated/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof AuthenticatedMuralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/motociclistas': {
      id: '/_authenticated/motociclistas'
      path: '/motociclistas'
      fullPath: '/motociclistas'
      preLoaderRoute: typeof AuthenticatedMotociclistasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instrucoes': {
      id: '/_authenticated/instrucoes'
      path: '/instrucoes'
      fullPath: '/instrucoes'
      preLoaderRoute: typeof AuthenticatedInstrucoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/corridas': {
      id: '/_authenticated/corridas'
      path: '/corridas'
      fullPath: '/corridas'
      preLoaderRoute: typeof AuthenticatedCorridasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat-motociclistas': {
      id: '/_authenticated/chat-motociclistas'
      path: '/chat-motociclistas'
      fullPath: '/chat-motociclistas'
      preLoaderRoute: typeof AuthenticatedChatMotociclistasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat-clientes': {
      id: '/_authenticated/chat-clientes'
      path: '/chat-clientes'
      fullPath: '/chat-clientes'
      preLoaderRoute: typeof AuthenticatedChatClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/cliente/app/': {
      id: '/cliente/app/'
      path: '/'
      fullPath: '/cliente/app/'
      preLoaderRoute: typeof ClienteAppIndexRouteImport
      parentRoute: typeof ClienteAppRoute
    }
    '/cliente/app/senha': {
      id: '/cliente/app/senha'
      path: '/senha'
      fullPath: '/cliente/app/senha'
      preLoaderRoute: typeof ClienteAppSenhaRouteImport
      parentRoute: typeof ClienteAppRoute
    }
    '/cliente/app/perfil': {
      id: '/cliente/app/perfil'
      path: '/perfil'
      fullPath: '/cliente/app/perfil'
      preLoaderRoute: typeof ClienteAppPerfilRouteImport
      parentRoute: typeof ClienteAppRoute
    }
    '/cliente/app/historico': {
      id: '/cliente/app/historico'
      path: '/historico'
      fullPath: '/cliente/app/historico'
      preLoaderRoute: typeof ClienteAppHistoricoRouteImport
      parentRoute: typeof ClienteAppRoute
    }
    '/cliente/app/chat': {
      id: '/cliente/app/chat'
      path: '/chat'
      fullPath: '/cliente/app/chat'
      preLoaderRoute: typeof ClienteAppChatRouteImport
      parentRoute: typeof ClienteAppRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedChatClientesRoute: typeof AuthenticatedChatClientesRoute
  AuthenticatedChatMotociclistasRoute: typeof AuthenticatedChatMotociclistasRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCorridasRoute: typeof AuthenticatedCorridasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedInstrucoesRoute: typeof AuthenticatedInstrucoesRoute
  AuthenticatedMotociclistasRoute: typeof AuthenticatedMotociclistasRoute
  AuthenticatedMuralRoute: typeof AuthenticatedMuralRoute
  AuthenticatedTarifasRoute: typeof AuthenticatedTarifasRoute
  AuthenticatedTermosConfigRoute: typeof AuthenticatedTermosConfigRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedChatClientesRoute: AuthenticatedChatClientesRoute,
  AuthenticatedChatMotociclistasRoute: AuthenticatedChatMotociclistasRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCorridasRoute: AuthenticatedCorridasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedInstrucoesRoute: AuthenticatedInstrucoesRoute,
  AuthenticatedMotociclistasRoute: AuthenticatedMotociclistasRoute,
  AuthenticatedMuralRoute: AuthenticatedMuralRoute,
  AuthenticatedTarifasRoute: AuthenticatedTarifasRoute,
  AuthenticatedTermosConfigRoute: AuthenticatedTermosConfigRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ClienteAppRouteChildren {
  ClienteAppChatRoute: typeof ClienteAppChatRoute
  ClienteAppHistoricoRoute: typeof ClienteAppHistoricoRoute
  ClienteAppPerfilRoute: typeof ClienteAppPerfilRoute
  ClienteAppSenhaRoute: typeof ClienteAppSenhaRoute
  ClienteAppIndexRoute: typeof ClienteAppIndexRoute
}

const ClienteAppRouteChildren: ClienteAppRouteChildren = {
  ClienteAppChatRoute: ClienteAppChatRoute,
  ClienteAppHistoricoRoute: ClienteAppHistoricoRoute,
  ClienteAppPerfilRoute: ClienteAppPerfilRoute,
  ClienteAppSenhaRoute: ClienteAppSenhaRoute,
  ClienteAppIndexRoute: ClienteAppIndexRoute,
}

const ClienteAppRouteWithChildren = ClienteAppRoute._addFileChildren(
  ClienteAppRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ComoFuncionaRoute: ComoFuncionaRoute,
  InstalarRoute: InstalarRoute,
  MotociclistaRoute: MotociclistaRoute,
  PainelRoute: PainelRoute,
  ParceirosRoute: ParceirosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  ClienteAppRoute: ClienteAppRouteWithChildren,
  ClienteCadastroRoute: ClienteCadastroRoute,
  ClienteEsqueciSenhaRoute: ClienteEsqueciSenhaRoute,
  ClienteLoginRoute: ClienteLoginRoute,
  ClienteRedefinirSenhaRoute: ClienteRedefinirSenhaRoute,
  OperadorLoginRoute: OperadorLoginRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
